Add button for deleting content
JoaoPauloBorges/angular-blitzlcc pull request #9
Opened 2020-03-30 19:15 UTC by rafaelgssa

Resolves #5

2020-05-19 11:48 UTC, JoaoPauloBorges requested changes
Cara ficou bacana, só está faltando implementar o delete das imagens referentes aos contents, pq o content vai ser apagado e elas vão ficar perdidas lá no banco de dados.

2020-06-02 02:26 UTC, JoaoPauloBorges approved these changes

2020-06-02 02:33 UTC, merged

2020-06-02 12:32 UTC, rafaelgssa commented
Foi mal pela demora na implementação. As últimas semanas foram um pouco corridas com relatórios e TCC, e eu realmente não tive tempo.

2020-06-04 12:11 UTC, JoaoPauloBorges commented
Tranquilo rafael, as coisas estão corridas por aqui também, por isso o projeto ficou meio parado, mas em relação ao PR era só um ajuste que tinha que fazer lá nos models, de boa 👍